language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install pep8 --use-mirrors
  - pip install coverage --use-mirrors
script:
  - make test
notifications:
  email:
    - phihag@phihag.de
    - liebig.richard@hotmail.com
